apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN octopus
  labels:
    k8s-app: octopus
    location: lan
  name: octopus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: octopus
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN octopus
      creationTimestamp: null
      labels:
        k8s-app: octopus
        location: lan
      name: octopus
    spec:
      containers:
      - env:
        - name: tz
          value: Europe/Berlin
        image: marvinmarvin/docker-k8s-octopus
        imagePullPolicy: Always
        name: octopus
        volumeMounts:
        - mountPath: /etc/cron.d
          name: k8s-octopus
          subPath: octopus
        resources: {}
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
#      - name: k8s-cfg-octopus
#        hostPath:
#          path: /root/k8s-cfg/octopus
#          type: Directory         
      - name: k8s-octopus
        persistentVolumeClaim:
          claimName: k8s-pvc
      dnsPolicy: ClusterFirst
      hostNetwork: false
      nodeSelector:
        location: lan
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
