FROM marvinmarvin/docker-k8s-rclone:amd64
RUN apt-get update -y && \
    apt-get install git nodejs npm wget -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN npm install --global @deptagency/octopus
RUN which octopus
