#
FROM marvinmarvin/docker-k8s-rclone:amd64
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends git nodejs npm wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN npm config set unsafe-perm true
RUN npm config set strict-ssl false
RUN npm install --global @deptagency/octopus
RUN which octopus
